version: "3.7"
services:
    db:
        image: mysql:8
        restart: always
        container_name: myapp-db
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: Online_Store_one
            MYSQL_USERNAME: root
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        ports:
            - "33066:3306"
        volumes:
            - ./storage/mysql-data:/var/lib/mysql
            - ./docker/dev/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
        networks:
          - app-network
    app:
        build:
            context: .
            dockerfile: ./Dockerfile
        restart: always
        container_name: myapp-web
        entrypoint: ["/var/www/myapp/setup.sh"]
        command: bash -c "php artisan serve --host=0.0.0.0 --port=8000"
        depends_on:
            - db
        ports:
            - "8000:8000"
        volumes:
            - ./:/var/www/myapp
        networks:
          - app-network

volumes:
    web-app:
        driver: local
# Docker Networks
networks:
 app-network:
   driver: bridge